[package]
name = "hai606i_sudoku"
version = "0.0.1"
edition = "2021"
default-run = "hai606i_sudoku"

[dependencies]
env_logger = "0.11.6"
graph = "0.3.1"
log = "0.4.25"
macroquad = "0.4"
rand = "0.8.5"
