name: Test and build with and witout features on push / pull request

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Tests
              run: cargo test -- --nocapture
            - name: Build release without database
              run: cargo build -r
            - name: Build release with database
              run: cargo build -r --all-features
